model: autodeeplab
batch_size: 8
n_epochs: 100
lr: 0.003
train_fpath: /workspace/skin-lesion-segmentation-agreement/data/train_isic_titans_clean.txt
val_fpath: /workspace/skin-lesion-segmentation-agreement/data/validation_isic_titans_clean.txt
train_conditioning: bounding_box
val_conditioning: bounding_box
multimask: true
patience: 100