model: autodeeplab
batch_size: 8
n_epochs: 100
lr: 0.003
train_fpath: /workspace/skin/data/train_isic_titans_full.txt
val_fpath: /workspace/skin/data/validation_isic_titans_full.txt
train_conditioning: bounding_box
val_conditioning: bounding_box
multimask: true
patience: 100